name: Release

# Only release when a new GH tag is added
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      dockerhub: docker.io/alvneiayu/sealed-secrets-controller
      ghcr: ghcr.io/alvneiayu/sealed-secrets
      controller_image_name: sealed-secrets-controller
      kubeseal_image_name: sealed-secrets-kubeseal
    strategy:
      matrix:
        include:
          - dockerfile: ./docker/controller.Dockerfile
            image: ghcr.io/alvneiayu/sealed-secrets/sealed-secrets-controller
          - dockerfile: ./docker/kubeseal.Dockerfile
            image: docker.io/alvneiayu/sealed-secrets/sealed-secrets-kubeseal
          - dockerfile: ./docker/kubeseal.Dockerfile
            image: ghcr.io/alvneiayu/sealed-secrets/sealed-secrets-kubeseal
          - dockerfile: ./docker/controller.Dockerfile
            image: docker.io/alvneiayu/sealed-secrets/sealed-secrets-controller

    steps:
      # Checkout and set env
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.5
      - name: Setup kubecfg
        run: |
          mkdir -p ~/bin
          curl -sLf https://github.com/kubecfg/kubecfg/releases/download/v0.26.0/kubecfg_Linux_X64 >~/bin/kubecfg
          chmod +x ~/bin/kubecfg

      - name: Install dependencies
        run: |
          go install gotest.tools/gotestsum@v1.8.1

      # Run tests
      - name: Tests
        run: make test

      # Generate K8s manifests
      - name: K8s manifests
        run: |
          export PATH=~/bin:$PATH
          make CONTROLLER_IMAGE=${{ env.dockerhub }}/${{ env.controller_image_name }}:${{ github.ref_name }} controller.yaml controller-norbac.yaml

      # Setup env for multi-arch builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build & Release binaries
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: v1.10.3
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Build & Publish multi-arch image
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Login to GHRC
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          tags: ${{ steps.meta.outputs.tags }}
